from __future__ import annotations

import getpass
import secrets
from pathlib import Path
from typing import Any

import yaml

from mobius.config import load_config


def default_config_path() -> Path:
    candidate = Path("/etc/mobius/config.yaml")
    if candidate.exists():
        return candidate
    return Path("config.yaml")


def default_env_path() -> Path:
    candidate = Path("/etc/mobius/mobius.env")
    if candidate.exists():
        return candidate
    return Path(".env")


def _parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def _write_env_file(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Mobius environment values",
        "# Generated by: mobius onboarding",
        "",
        f"OPENAI_API_KEY={values.get('OPENAI_API_KEY', '')}",
        f"GEMINI_API_KEY={values.get('GEMINI_API_KEY', '')}",
        f"MOBIUS_API_KEY={values.get('MOBIUS_API_KEY', '')}",
        f"MOBIUS_STATE_DSN={values.get('MOBIUS_STATE_DSN', '')}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError:
        pass


def _prompt_text(prompt: str, current: str = "") -> str:
    suffix = f" [{current}]" if current else ""
    value = input(f"{prompt}{suffix}: ").strip()
    return value if value else current


def _prompt_secret(prompt: str, current: str = "") -> str:
    hint = " [set]" if current else ""
    value = getpass.getpass(f"{prompt}{hint}: ").strip()
    return value if value else current


def _prompt_confirm(prompt: str, default: bool = False) -> bool:
    suffix = " [Y/n]" if default else " [y/N]"
    try:
        raw = input(f"{prompt}{suffix}: ").strip().lower()
    except EOFError:
        return default
    if not raw:
        return default
    return raw in {"y", "yes"}


def _prompt_existing_data_mode() -> str:
    print("Choose how to proceed:")
    print("  [k] keep existing values as defaults and continue onboarding")
    print("  [o] overwrite existing values during onboarding")
    print("  [c] cancel")
    while True:
        try:
            raw = input("Selection [k/o/c] (default: k): ").strip().lower()
        except EOFError:
            return "keep"
        if raw in {"", "k", "keep"}:
            return "keep"
        if raw in {"o", "overwrite"}:
            return "overwrite"
        if raw in {"c", "cancel"}:
            return "cancel"
        print("Invalid selection. Please enter k, o, or c.")


def _is_meaningful_secret(value: str | None) -> bool:
    raw = (value or "").strip()
    if not raw:
        return False
    return raw.lower() not in {"change-me", "replace-me", "changeme"}


def _as_dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _existing_setup_signals(
    raw_cfg: dict[str, Any],
    env_values: dict[str, str],
) -> list[str]:
    signals: list[str] = []
    if _is_meaningful_secret(env_values.get("MOBIUS_API_KEY")):
        signals.append("MOBIUS_API_KEY is already configured in env file.")
    if _is_meaningful_secret(env_values.get("OPENAI_API_KEY")):
        signals.append("OPENAI_API_KEY is already configured in env file.")
    if _is_meaningful_secret(env_values.get("GEMINI_API_KEY")):
        signals.append("GEMINI_API_KEY is already configured in env file.")
    if _is_meaningful_secret(env_values.get("MOBIUS_STATE_DSN")):
        signals.append("MOBIUS_STATE_DSN is already configured in env file.")

    server = _as_dict(raw_cfg.get("server"))
    api_keys = server.get("api_keys")
    if isinstance(api_keys, list) and any(str(item or "").strip() for item in api_keys):
        signals.append("server.api_keys already has configured values.")

    return signals


def _coerce_port(value: Any, fallback: int = 8080) -> int:
    try:
        return int(str(value).strip())
    except Exception:
        return fallback


def _load_raw_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    loaded = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return loaded if isinstance(loaded, dict) else {}


def _save_yaml(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        yaml.safe_dump(data, sort_keys=False, allow_unicode=False),
        encoding="utf-8",
    )


def run_onboarding(
    config_path: str | Path | None = None,
    env_file: str | Path | None = None,
    force: bool = False,
) -> None:
    cfg_path = Path(config_path) if config_path else default_config_path()
    env_path = Path(env_file) if env_file else default_env_path()

    config = None
    try:
        config = load_config(cfg_path)
    except Exception:
        config = None
    raw = _load_raw_yaml(cfg_path)
    existing_env = _parse_env_file(env_path)
    signals = _existing_setup_signals(raw, existing_env)

    print("")
    print("Mobius Onboarding")
    print("=================")
    print(f"Config file: {cfg_path}")
    print(f"Env file:    {env_path}")
    print("")

    if signals and not force:
        print("Existing onboarding data detected:")
        for signal in signals:
            print(f"- {signal}")
        print("")
        mode = _prompt_existing_data_mode()
        if mode == "cancel":
            print("Onboarding cancelled. No files were modified.")
            print("")
            return
        if mode == "keep":
            print("Continuing onboarding with existing values as defaults.")
        else:
            print("Continuing onboarding in overwrite mode.")
        print("")

    raw_server = _as_dict(raw.get("server"))
    raw_specialists = _as_dict(raw.get("specialists"))
    host_default = config.server.host if config is not None else str(
        raw_server.get("host", "0.0.0.0")
    )
    port_default = (
        config.server.port
        if config is not None
        else _coerce_port(raw_server.get("port"), fallback=8080)
    )
    prompts_default = (
        str(config.specialists.prompts_directory)
        if config is not None
        else str(raw_specialists.get("prompts_directory", "./system_prompts"))
    )
    state_enabled_default = (
        bool(config.state.enabled)
        if config is not None
        else bool(_as_dict(raw.get("state")).get("enabled", False))
    )
    state_dsn_default = existing_env.get("MOBIUS_STATE_DSN", "")

    openai_key = _prompt_secret(
        "OpenAI API key",
        existing_env.get("OPENAI_API_KEY", ""),
    )
    gemini_key = _prompt_secret(
        "Gemini API key (optional)",
        existing_env.get("GEMINI_API_KEY", ""),
    )
    generated_key = f"sk-mobius-{secrets.token_urlsafe(24)}"
    mobius_api_key = _prompt_secret(
        "Mobius API key (used by Open WebUI)",
        existing_env.get("MOBIUS_API_KEY", generated_key),
    )

    host = _prompt_text("Service host", host_default)
    port_text = _prompt_text("Service port", str(port_default))
    try:
        port = int(port_text)
    except ValueError:
        port = port_default

    prompts_dir = _prompt_text(
        "System prompts directory",
        prompts_default,
    )
    state_enabled = _prompt_confirm(
        "Enable stateful pipeline (check-ins/journal/memory)?",
        default=state_enabled_default,
    )
    state_dsn = _prompt_secret(
        "State Postgres DSN",
        state_dsn_default if state_enabled else "",
    )

    _write_env_file(
        env_path,
        {
            "OPENAI_API_KEY": openai_key,
            "GEMINI_API_KEY": gemini_key,
            "MOBIUS_API_KEY": mobius_api_key,
            "MOBIUS_STATE_DSN": state_dsn if state_enabled else "",
        },
    )

    raw.setdefault("server", {})
    raw["server"]["host"] = host
    raw["server"]["port"] = port
    raw["server"]["api_keys"] = ["${ENV:MOBIUS_API_KEY}"]

    raw.setdefault("providers", {})
    raw["providers"].setdefault("openai", {})
    raw["providers"].setdefault("gemini", {})
    raw["providers"]["openai"]["api_key"] = "${ENV:OPENAI_API_KEY}"
    raw["providers"]["gemini"]["api_key"] = "${ENV:GEMINI_API_KEY}"

    raw.setdefault("specialists", {})
    raw["specialists"]["prompts_directory"] = prompts_dir

    raw.setdefault("state", {})
    raw["state"]["enabled"] = state_enabled
    raw["state"].setdefault("database", {})
    raw["state"]["database"]["dsn"] = "${ENV:MOBIUS_STATE_DSN}"

    _save_yaml(cfg_path, raw)

    print("")
    print("Onboarding complete.")
    print("")
    print("Next steps:")
    print(f"1) Review config: {cfg_path}")
    print(f"2) Review env:    {env_path}")
    print("3) Restart service:")
    print("   systemctl restart mobius")
    print("4) Verify:")
    print("   mobius diagnostics")
    print("5) Open WebUI -> Admin Settings -> Connections -> OpenAI")
    print("   Base URL: http://<mobius-ip>:8080/v1")
    print("   API Key:  value of MOBIUS_API_KEY")
    print("")
