from __future__ import annotations

import getpass
import secrets
from pathlib import Path
from typing import Any

import yaml

from ai_agents_hub.config import load_config


def _default_config_path() -> Path:
    candidate = Path("/etc/ai-agents-hub/config.yaml")
    if candidate.exists():
        return candidate
    return Path("config.yaml")


def _default_env_path() -> Path:
    candidate = Path("/etc/ai-agents-hub/ai-agents-hub.env")
    if candidate.exists():
        return candidate
    return Path(".env")


def _parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def _write_env_file(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# AI Agents Hub environment values",
        "# Generated by: ai-agents-hub onboard",
        "",
        f"OPENAI_API_KEY={values.get('OPENAI_API_KEY', '')}",
        f"GEMINI_API_KEY={values.get('GEMINI_API_KEY', '')}",
        f"AI_AGENTS_HUB_API_KEY={values.get('AI_AGENTS_HUB_API_KEY', '')}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError:
        pass


def _prompt_text(prompt: str, current: str = "") -> str:
    suffix = f" [{current}]" if current else ""
    value = input(f"{prompt}{suffix}: ").strip()
    return value if value else current


def _prompt_secret(prompt: str, current: str = "") -> str:
    hint = " [set]" if current else ""
    value = getpass.getpass(f"{prompt}{hint}: ").strip()
    return value if value else current


def _load_raw_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    loaded = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return loaded if isinstance(loaded, dict) else {}


def _save_yaml(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        yaml.safe_dump(data, sort_keys=False, allow_unicode=False),
        encoding="utf-8",
    )


def run_onboarding(
    config_path: str | Path | None = None,
    env_file: str | Path | None = None,
) -> None:
    cfg_path = Path(config_path) if config_path else _default_config_path()
    env_path = Path(env_file) if env_file else _default_env_path()

    config = load_config(cfg_path)
    existing_env = _parse_env_file(env_path)

    print("")
    print("AI Agents Hub Onboarding")
    print("========================")
    print(f"Config file: {cfg_path}")
    print(f"Env file:    {env_path}")
    print("")

    openai_key = _prompt_secret(
        "OpenAI API key",
        existing_env.get("OPENAI_API_KEY", ""),
    )
    gemini_key = _prompt_secret(
        "Gemini API key (optional)",
        existing_env.get("GEMINI_API_KEY", ""),
    )
    generated_key = f"sk-ahub-{secrets.token_urlsafe(24)}"
    hub_key = _prompt_secret(
        "AI Agents Hub API key (used by Open WebUI)",
        existing_env.get("AI_AGENTS_HUB_API_KEY", generated_key),
    )

    host = _prompt_text("Service host", config.server.host)
    port_text = _prompt_text("Service port", str(config.server.port))
    try:
        port = int(port_text)
    except ValueError:
        port = config.server.port

    prompts_dir = _prompt_text(
        "Specialist prompts directory",
        str(config.specialists.prompts.directory),
    )

    _write_env_file(
        env_path,
        {
            "OPENAI_API_KEY": openai_key,
            "GEMINI_API_KEY": gemini_key,
            "AI_AGENTS_HUB_API_KEY": hub_key,
        },
    )

    raw = _load_raw_yaml(cfg_path)
    raw.setdefault("server", {})
    raw["server"]["host"] = host
    raw["server"]["port"] = port
    raw["server"]["api_keys"] = ["${ENV:AI_AGENTS_HUB_API_KEY}"]

    raw.setdefault("providers", {})
    raw["providers"].setdefault("openai", {})
    raw["providers"].setdefault("gemini", {})
    raw["providers"]["openai"]["api_key"] = "${ENV:OPENAI_API_KEY}"
    raw["providers"]["gemini"]["api_key"] = "${ENV:GEMINI_API_KEY}"

    raw.setdefault("specialists", {})
    raw["specialists"].setdefault("prompts", {})
    raw["specialists"]["prompts"]["directory"] = prompts_dir

    _save_yaml(cfg_path, raw)

    print("")
    print("Onboarding complete.")
    print("")
    print("Next steps:")
    print(f"1) Review config: {cfg_path}")
    print(f"2) Review env:    {env_path}")
    print("3) Restart service:")
    print("   systemctl restart ai-agents-hub")
    print("4) Verify:")
    print("   curl http://<host-or-ip>:8080/healthz")
    print("   curl http://<host-or-ip>:8080/readyz")
    print("   curl http://<host-or-ip>:8080/diagnostics")
    print("5) Open WebUI -> Admin Settings -> Connections -> OpenAI")
    print("   Base URL: http://<ai-agents-hub-ip>:8080/v1")
    print("   API Key:  value of AI_AGENTS_HUB_API_KEY")
    print("")
